version: '3.3'

services:
  datacenter:
    container_name: datacenter
    build:
      context: datacenter
      dockerfile: datacenter.Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./datacenter:/app
    links:
      - db
    depends_on: 
      - db

  monitoring:
    container_name: monitoring
    build:
      context: monitoring
      dockerfile: monitoring.Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./monitoring:/app
    links:
      - db
    depends_on: 
      - db

  db:
    image: influxdb:latest 
    container_name: monitoring-influxdb
    restart: always
    ports:
      - "8086:8086"
